---
title: "Homework_DataVis2"
author: "Priya Shahi"
date: "2026-02-26"
output: 
  md_document:
      variant: gfm
  html_document:
  pdf_document:
    toc: true
    number_sections: true
    toc_depth: 3
  word_document:
---
# Figure2a
```{r}
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(tidyverse)

cbbPalette <- c("#E69F00", "#56B4E9", "#009E73")
sample.data.bac <- read.csv("BacterialAlpha.csv", na.strings = "na")
head(sample.data.bac)
sample.data.bac$Time_Point <- as.factor(sample.data.bac$Time_Point)
sample.data.bac$Crop <- as.factor(sample.data.bac$Crop)
sample.data.bac$Crop <- factor(sample.data.bac$Crop, levels = c("Soil", "Cotton", "Soybean"))

str(sample.data.bac)

```
```{r}
####### Bacterial evenness; Figure 2a ########
bac.even <- ggplot(sample.data.bac, aes(x = Time_Point, y = even, color = Crop)) +  # Define aesthetics: x-axis as Time.Point, y-axis as even, and color by Crop
  geom_boxplot(position = position_dodge(0.85)) +  # Add boxplots with dodged positions to avoid overlap
  geom_point(position = position_jitterdodge(0.05)) +  # Add jittered points to show individual data points, avoiding overlap
  ylab("Pielou's evenness") +  # Label the y-axis
  xlab("Hours post sowing") +  # Label the x-axis
  scale_color_manual(values = cbbPalette, name = "", labels = c("Soil no seeds", "Cotton spermosphere", "Soybean spermosphere")) +  # Manually set colors and labels for the Crop variable
  theme_classic()   # Use a classic theme for the plot
bac.even

```



```{r}
bac.even <- ggplot(sample.data.bac, 
                   aes(x = Time_Point, y = even, color = Crop)) +
  geom_boxplot(position = position_dodge(0.85)) +
  geom_point(shape = 21, fill = "white", color = "black",
             position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.85)) +
  ylab("Pielou's evenness") +
  xlab("Hours post sowing") +
  scale_color_manual(
    values = c("#E69F00", "#56B4E9", "#009E73"),  # three distinct colors
    name = "",
    labels = c("Soil no seeds", "Cotton spermosphere", "Soybean spermosphere")
  ) +
  theme_classic()

bac.even
```


# Figure2b
```{r}
####### Water Imbibition correlate with bacterial evenness; Figure 2b #####

sample.data.bac.nosoil <- subset(sample.data.bac, Crop != "Soil")

water.imbibed <- ggplot(sample.data.bac.nosoil, 
                        aes(Time_Point, 1000 * Water_Imbibed, color = Crop)) +  
  geom_jitter(width = 0.5, alpha = 0.5) +  
  stat_summary(fun = mean, geom = "line", aes(group = Crop)) +  
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.5) +  
  xlab("Hours post sowing") +  
  ylab("Water Imbibed (mg)") +  
  scale_color_manual(
    values = c("#56B4E9", "#009E73"),  # two valid colors
    name = "",
    labels = c("Cotton", "Soybean")
  ) +  
  theme_classic() +  
  theme(strip.background = element_blank(), legend.position = "none") +  
  facet_wrap(~Crop, scales = "free")

water.imbibed
```


# Figure2c
```{r}
##### Figure 2c #####
water.imbibed.cor <- ggplot(sample.data.bac.nosoil,
                            aes(x = 1000 * Water_Imbibed,
                                y = even,
                                color = Crop)) +
  
  geom_point(aes(shape = Time_Point), size = 3) +   # Points indexed by Time_Point
  
  geom_smooth(method = lm,
              se = FALSE,
              aes(group = Crop)) +   # One regression line per Crop
  
  xlab("Water Imbibed (mg)") +
  ylab("Pielou's evenness") +
  
  scale_color_manual(
    values = c(cbbPalette[[1]], cbbPalette[[2]]),
    name = ""
  ) +
  
  scale_shape_manual(
    values = c(15, 16, 17, 18),
    name = "",
    labels = c("0 hrs", "6 hrs", "12 hrs", "18 hrs")
  ) +
  
  theme_classic() +
  theme(strip.background = element_blank()) +
  
  facet_wrap(~Crop, scales = "free")

water.imbibed.cor




```

```{r}

library(ggpubr)
```

# Combine Figure2
```{r}
# Arrange multiple ggplot objects into a single figure
figure2 <- ggarrange(
  water.imbibed,  # First plot: water.imbibed
  bac.even,  # Second plot: bac.even
  water.imbibed.cor,  # Third plot: water.imbibed.cor
  labels = "auto",  # Automatically label the plots (A, B, C, etc.)
  nrow = 3,  # Arrange the plots in 3 rows
  ncol = 1,  # Arrange the plots in 1 column
  legend = FALSE  # Do not include a legend in the combined figure
)

figure2




```


# Signficance
```{r}
bac.even + 
  stat_compare_means(method = "anova") # apply an anova to the groups
### Example with pvalues as significance levels
bac.even + 
  geom_pwc(aes(group = Crop), method = "t_test", label = "p.adj.format")
```

```{r}
### example with * as significance levels
bac.even + 
  geom_pwc(aes(group = Crop), method = "t_test", label = "p.adj.signif")

```


```{r}

### Example with combined pvalue and * to indicate significance
bac.even + 
  geom_pwc(aes(group = Crop), method = "t_test", label = "{p.adj.format}{p.adj.signif}")

```


```{r}
water.imbibed.cor + 
  stat_cor()



water.imbibed.cor + 
  stat_cor(label.y = 0.7) +
  stat_regline_equation()
```


```{r}
diff.abund <- read.csv("diff_abund.csv", na.strings = 'na')
str(diff.abund)
head(diff.abund)
```


# Make a volcano plot for Soybean vs. Soil
```{r}
#Make a volcano plot for Soybean vs. Soil

diff.abund$log10_pvalue <- -log10(diff.abund$p_CropSoybean)
diff.abund.label <- diff.abund[diff.abund$log10_pvalue > 30,]


#Make the plot

ggplot() + 
  geom_point(data = diff.abund, aes(x = lfc_CropSoybean, y = log10_pvalue, color = diff_CropSoybean)) + 
  theme_classic() + 
  geom_text_repel(data = diff.abund.label, aes(x = lfc_CropSoybean, y = log10_pvalue, color = diff_CropSoybean, label = Label))


```


# Volcano 1
```{r}
volcano <- ggplot() + 
  geom_point(data = diff.abund, aes(x = lfc_CropSoybean, y = log10_pvalue, color = diff_CropSoybean)) + 
  geom_text_repel(data = diff.abund.label, aes(x = lfc_CropSoybean, y = log10_pvalue, color = diff_CropSoybean, label = Label)) + 
  scale_color_manual(values = cbbPalette, name = "Significant") +
  theme_classic() + 
  xlab("Log fold change Soil vs. Soybean") +
  ylab("-log10 p-value")
volcano
```




# Volcano 2
```{r}
volcano <- ggplot() + 
  geom_point(data = diff.abund, aes(x = lfc_CropSoybean, y = log10_pvalue)) + 
  geom_point(data = diff.abund.label, aes(x = lfc_CropSoybean, y = log10_pvalue), color = "red", shape = 17, size = 4) +
  geom_text_repel(data = diff.abund.label, aes(x = lfc_CropSoybean, y = log10_pvalue, label = Label), color = "red") + 
  theme_classic() + 
  xlab("Log fold change Soil vs. Soybean") +
  ylab("-log10 p-value")
volcano

```







