---
title: "CodingChallenge$"
author: "Priya Shahi"
date: "2026-02-20"
output: 
  
  md_document:
    variant: gfm
  html_document:
    toc: True
    toc_float: True
  pdf_document:  
  word_document:
---
# CodingChallenge4
```{r }
library(tidyverse)
library(ggpubr) 
```

# Load data
```{r load data}
mycotoxin = read.csv(file.choose(),na.strings = "na")
```

# Plot 1
```{r}
# Plot 1 pairwise comparisons 
Plot1_pwc <- Plot1 +
  geom_pwc(aes(group = Treatment), method = "t.test", label = "p.adj.format") +  # Add pairwise t-tests
  theme_classic()

Plot1_pwc
```


# Plot 2
```{r}
# Plot 2 pairwise comparisons
Plot2_pwc <- Plot2 +
  geom_pwc(aes(group=Treatment), method= "t.test", label= "p.adj.format")+
  theme_classic()

Plot2_pwc
```


# Plot 3
```{r}
# Plot 3 pairwise comparisons
Plot3_pwc = Plot3 + geom_pwc(aes(group=Treatment), method="t.test", label="p.adj.format")+
  theme_classic()

Plot3_pwc

```

# Combine Plot
```{r}
# Combine all three plots with a common legend ----
Combined_pwc =ggarrange(
  Plot1_pwc,
  Plot2_pwc,
  Plot3_pwc, labels = "AUTO", nrow = 1, ncol = 3, common.legend = T)

Combined_pwc
```



